services:
  postgres:
    image: postgres:15-alpine
    container_name: modernhomm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_bot
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - modernhomm_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modernhomm_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/telegram_bot
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    networks:
      - modernhomm_network

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: modernhomm_admin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/telegram_bot
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
    restart: unless-stopped
    networks:
      - modernhomm_network

networks:
  modernhomm_network:
    driver: bridge
